// Plan features for LawCFO
// Auto-generated by Jarvis Pipeline

export const PLAN_FEATURES = {
  essential: {
    name: "Essential",
    price: 249,
    features: [
    "Core Financial Dashboard",
    "Key Performance Indicators (KPIs)",
    "Real-time Data Sync (Clio, MyCase, QuickBooks, LawPay)",
    "Basic P&L, Balance Sheet, Cash Flow Statements",
    "WIP & AR Aging Reports",
    "Basic Trust Account Monitoring",
    "Up to 10 Users"
    ],
  },
  professional: {
    name: "Professional",
    price: 499,
    features: [
    "Essential +",
    "Advanced Profitability Analytics (by Matter, Attorney, Practice Area)",
    "Customizable Dashboards & Reports",
    "Cash Flow Forecasting",
    "Budgeting & Variance Analysis",
    "Attorney Utilization & Realization Tracking",
    "Additional Integrations (PracticePanther, Xero)",
    "Email & Chat Support",
    "Up to 25 Users"
    ],
  },
  enterprise: {
    name: "Enterprise",
    price: 999,
    features: [
    "Professional +",
    "Multi-Firm/Entity Support",
    "Advanced Scenario Planning & Modeling",
    "Dedicated AI CFO Advisor with Custom Prompts",
    "API Access for Custom Integrations",
    "Priority Onboarding & Dedicated Account Manager",
    "Enhanced Security & Compliance Features",
    "Unlimited Users"
    ],
  },
} as const;

export type PlanTier = keyof typeof PLAN_FEATURES;
